apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  labels:
    app: product-review
type: Opaque
stringData:
  MONGODB_URI: "mongodb://congphuc4:CongPhuc2206@10.0.11.49:27017,10.0.11.114:27017,10.0.11.71:27017,10.0.11.80:27017/productsReviewDB?replicaSet=replicaset&authSource=productsReviewDB&readPreference=secondaryPreferred"
